text_recognition example argparse bug fix
The text recognition CRNN demo.py argument parser is incomplete.

Running

```
python3 demo.py --input ./examples/demo.jpg
```

yields the following error:

```
Traceback (most recent call last):
  File "opencv_zoo/models/text_recognition_crnn/demo.py", line 75, in <module>
    image = cv.resize(image, [args.width, args.height])
AttributeError: 'Namespace' object has no attribute 'width'
```

Error is caused by incomplete copy&paste of the argument parser of the `demo.py` in the text detection example.
This pull request fixes that.